resolver: lts-6.1

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: https://github.com/TokTok/hs-msgpack.git
    commit: d2b78df9d4b109d9a8b1fdbd1d374f50af0c34e1
  extra-dep: true

nix:
    enable: false
    packages: [openssh,git]

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
